### ISSUE TITLE
raise ValueError('need at least one array to stack')

### ISSUE THREAD

**Issue by williamxhero** [HelloVision/ComfyUI_HelloMeme#10]
<img width="582" alt="Snipaste_2024-11-14_17-20-09" src="https://github.com/user-attachments/assets/b3c329c3-dd1e-4d40-91ed-ea1fb2ad7b57">

Prompt executed in 2.47 seconds
got prompt
create onnx session cost: 0.041s. C:\Users\admin\.cache\huggingface\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188\hello_face_landmark.onnx
create onnx session cost: 0.031s. C:\Users\admin\.cache\huggingface\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188\hello_face_det.onnx
create onnx session cost: 0.038s. C:\Users\admin\.cache\huggingface\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188\hello_arkit_blendshape.onnx
create onnx session cost: 0.752s. C:\Users\admin\.cache\huggingface\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188\hello_3dmm.onnx
DET stage1: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 168/168 [00:00<00:00, 200.31it/s]
0it [00:00, ?it/s]
!!! Exception during processing !!! need at least one array to stack
Traceback (most recent call last):
  File "D:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI_HelloMeme\meme.py", line 389, in get_face_params
    (drive_face_parts, drive_coeff, drive_rot, drive_trans) = get_drive_params(face_toolkits['face_aligner'],
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI_HelloMeme\hellomeme\utils.py", line 268, in get_drive_params
    frame_list, landmark_list = det_landmarks(face_aligner, frame_list, save_size=(512, 512), reset=False)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI_HelloMeme\hellomeme\utils.py", line 261, in det_landmarks
    save_landmark_list = np.stack(save_landmark_list, axis=0).astype(np.float16)
  File "C:\Users\admin\miniconda3\envs\comfyui_env\lib\site-packages\numpy\core\shape_base.py", line 445, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by songkey** [comment]
The code that directly triggered this issue has been fixed in the latest version. 
However, there is a deeper underlying problem: to ensure consistency between visuals and audio, we require every frame of the drive video to detect a face. 
If any face is missing in the drive video, the process will still fail.
