### ISSUE TITLE
Plugin node missing

### ISSUE THREAD

**Issue by idesign2018** [HelloVision/ComfyUI_HelloMeme#15]
I installed the ComfyUI_HelloMeme plugin, but when I add a workflow to ComfyUI, it still says that the node is missing. What's the reason? This happens to all workflows.
![image](https://github.com/user-attachments/assets/a33eae61-1d25-4c50-9496-3d9d0a9fee45)

**Comment by songkey** [comment]
It’s most likely an issue with the Python environment. Although I included logic in the code to automatically install missing packages, there’s still a chance it could fail. Here are two methods to manually resolve the issue:

1. Use the [environment.yml](https://github.com/HelloVision/ComfyUI_HelloMeme/blob/main/environment.yml) file in the code directory to create a new conda environment. This file was exported from my development environment and should be reliable.
2. On Windows, use the sandbox provided by ComfyUI's official setup. I have tested this, and it works effectively.

**Comment by idesign2018** [comment]
How to open the ComfyUI official sandbox? I am using the ComfyUI desktop version

**Comment by idesign2018** [comment]
I tried to reinstall and repair the problem repeatedly, but it didn't solve it

**Comment by swizardlv** [comment]
try to reinstall diffusers.  e.g. D:\AI_ART\ComfyUI-aki-v1.4\python>python.exe -m pip install -U diffusers

**Comment by janag-ui** [comment]
I have the same issue. I think this is the relevant error from the log:
```
ERROR: Invalid requirement: 'onnxruntime-gpu==1.18.1 onnx==1.17.0 peft==0.13.2': Expected end or semicolon (after version specifier)
    onnxruntime-gpu==1.18.1 onnx==1.17.0 peft==0.13.2
                   ~~~~~~~~~^
Traceback (most recent call last):
  File "S:\AMD\Programs\ComfyUI\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\AMD\Programs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_HelloMeme\__init__.py", line 1, in <module>
    from .meme import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "S:\AMD\Programs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_HelloMeme\meme.py", line 33, in <module>
    subprocess.check_call([python, '-m', 'pip', 'install', missing_params], stdout=subprocess.DEVNULL)
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['S:\\AMD\\Programs\\ComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'onnxruntime-gpu==1.18.1 onnx==1.17.0 peft==0.13.2']' returned non-zero exit status 1.

Cannot import S:\AMD\Programs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_HelloMeme module for custom nodes: Command '['S:\\AMD\\Programs\\ComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'onnxruntime-gpu==1.18.1 onnx==1.17.0 peft==0.13.2']' returned non-zero exit status 1.
```

Maybe the package dependencies passed as a single string to subprocess.CalledProcessError should be separate strings rather than a single space delimited string? I'll try to figure it out.

**Comment by janag-ui** [comment]
Below fixed the issue with the missing plugin nodes for me. Only tested on my Windows machine. In ComfyUI/custom_nodes/ComfyUI_HelloMeme/meme.py... Before fix:
```
missing_params = ' '.join([f'{k}=={REQUIRED[k]}' for k in missing])
print("missing pkgs", missing_params)

if missing:
    python = sys.executable
    subprocess.check_call([python, '-m', 'pip', 'install', missing_params], stdout=subprocess.DEVNULL)
```
After fix:
```
missing_params = [f'{k}=={REQUIRED[k]}' for k in missing]
print("missing pkgs", *missing_params)

if missing:
    python = sys.executable
    subprocess.check_call([python, '-m', 'pip', 'install'] + missing_params, stdout=subprocess.DEVNULL)
```
Unfortunately it later failed with another problem but I will file a separate issue for that, if appropriate.

**Comment by JohnZero2023** [comment]
> I have the same issue. I think this is the relevant error from the log:我有同样的问题。我认为这是日志中的相关错误：
> 
> ```
> ERROR: Invalid requirement: 'onnxruntime-gpu==1.18.1 onnx==1.17.0 peft==0.13.2': Expected end or semicolon (after version specifier)
>     onnxruntime-gpu==1.18.1 onnx==1.17.0 peft==0.13.2
>                    ~~~~~~~~~^
> Traceback (most recent call last):
>   File "S:\AMD\Programs\ComfyUI\ComfyUI\nodes.py", line 2035, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "S:\AMD\Programs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_HelloMeme\__init__.py", line 1, in <module>
>     from .meme import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "S:\AMD\Programs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_HelloMeme\meme.py", line 33, in <module>
>     subprocess.check_call([python, '-m', 'pip', 'install', missing_params], stdout=subprocess.DEVNULL)
>   File "subprocess.py", line 413, in check_call
> subprocess.CalledProcessError: Command '['S:\\AMD\\Programs\\ComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'onnxruntime-gpu==1.18.1 onnx==1.17.0 peft==0.13.2']' returned non-zero exit status 1.
> 
> Cannot import S:\AMD\Programs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_HelloMeme module for custom nodes: Command '['S:\\AMD\\Programs\\ComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'onnxruntime-gpu==1.18.1 onnx==1.17.0 peft==0.13.2']' returned non-zero exit status 1.
> ```
> 
> Maybe the package dependencies passed as a single string to subprocess.CalledProcessError should be separate strings rather than a single space delimited string? I'll try to figure it out.也许包依赖项作为单个字符串传递给 subprocess。CalledProcessError 应该是单独的字符串，而不是单个空格分隔的字符串？我会试着弄清楚。

Thank you bro, I solved this problem with your solution

**Comment by JohnZero2023** [comment]
> Below fixed the issue with the missing plugin nodes for me. Only tested on my Windows machine. In ComfyUI/custom_nodes/ComfyUI_HelloMeme/meme.py... Before fix:下面为我修复了缺少插件节点的问题。仅在我的 Windows 机器上测试过。在 ComfyUI/custom_nodes/ComfyUI_HelloMeme/meme.py...修复前：
> 
> ```
> missing_params = ' '.join([f'{k}=={REQUIRED[k]}' for k in missing])
> print("missing pkgs", missing_params)
> 
> if missing:
>     python = sys.executable
>     subprocess.check_call([python, '-m', 'pip', 'install', missing_params], stdout=subprocess.DEVNULL)
> ```
> 
> After fix:  修复后：
> 
> ```
> missing_params = [f'{k}=={REQUIRED[k]}' for k in missing]
> print("missing pkgs", *missing_params)
> 
> if missing:
>     python = sys.executable
>     subprocess.check_call([python, '-m', 'pip', 'install'] + missing_params, stdout=subprocess.DEVNULL)
> ```
> 
> Unfortunately it later failed with another problem but I will file a separate issue for that, if appropriate.不幸的是，它后来因另一个问题而失败，但如果合适，我将为此提交一个单独的问题。

Thank you bro, I solved this problem with your solution
